Bt_Th_6/Controllers/NhanVien63132691Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bt_Th_6.Models;

namespace Bt_Th_6.Controllers
{
    public class NhanVien63132691Controller : Controller
    {
        private QLNV63132691Entities db = new QLNV63132691Entities();

        // GET: NhanVien63132691
        string LayMaNV()
        {
            var maMax = db.NhanVien63132691.ToList().Select(n => n.MaNV).Max();
            int maNV = int.Parse(maMax.Substring(2)) + 1;
            string NV = String.Concat("000", maNV.ToString());
            return "NV" + NV.Substring(maNV.ToString().Length - 1);
        }
        public ActionResult Index()
        {
            var nhanViens = db.NhanVien63132691.Include(n => n.PhongBan);
            return View(nhanViens.ToList());
        }

        // GET: NhanVien63132691/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanVien63132691.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // GET: NhanVien63132691/Create
        public ActionResult Create()
        {
            ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB");
            return View();
        }

        // POST: NhanVien63132691/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaNV,HoNV,TenNV,GioiTinh,NgaySinh,Luong,AnhNV,DiaChi,MaPB")] NhanVien nhanVien)
        {
            //System.Web.HttpPostedFileBase Avatar;
            var imgNV = Request.Files["Avatar"];
            //Lấy thông tin từ input type=file có tên Avatar
            string postedFileName = System.IO.Path.GetFileName(imgNV.FileName);
            //Lưu hình đại diện về Server
            var path = Server.MapPath("/Images/" + postedFileName);
            imgNV.SaveAs(path);

            if (ModelState.IsValid)
            {
                nhanVien.MaNV = LayMaNV();
                nhanVien.AnhNV = postedFileName;
                db.NhanVien63132691.Add(nhanVien);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB", nhanVien.MaPB);
            return View(nhanVien);
        }

        // GET: NhanVien63132691/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanVien63132691.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB", nhanVien.MaPB);
            return View(nhanVien);
        }

        // POST: NhanVien63132691/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNV,HoNV,TenNV,GioiTinh,NgaySinh,Luong,AnhNV,DiaChi,MaPB")] NhanVien nhanVien)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhanVien).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaPB = new SelectList(db.PhongBans, "MaPB", "TenPB", nhanVien.MaPB);
            return View(nhanVien);
        }

        // GET: NhanVien63132691/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NhanVien nhanVien = db.NhanVien63132691.Find(id);
            if (nhanVien == null)
            {
                return HttpNotFound();
            }
            return View(nhanVien);
        }

        // POST: NhanVien63132691/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NhanVien nhanVien = db.NhanVien63132691.Find(id);
            db.NhanVien63132691.Remove(nhanVien);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult TimKiem63132691(string maNV = "", string hoTen = "")
        {
            ViewBag.maNV = maNV;
            ViewBag.hoTen = hoTen;
            var nhanViens = db.NhanVien63132691.SqlQuery("NhanVien_TimKiem'" + maNV + "','" + hoTen + "'");
            if (nhanViens.Count() == 0)
                ViewBag.TB = "Không có thông tin tìm kiếm.";
            return View(nhanViens.ToList());
        }
    }
}

Bt_Th_6/Views/NhanVien63132691/Create.cshtml
@model Bt_Th_6.Models.NhanVien

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h3>THÔNG TIN NHÂN VIÊN</h3>
@using (Html.BeginForm("Create", "NhanVien63132691", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group1">
            @Html.LabelFor(model => model.MaNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="text" value="@ViewBag.MaNV" disabled readonly class="form-control" />
                @*@Html.EditorFor(model => model.MaNV,"@ViewBag.MaNV", new { htmlAttributes = new { @class = "form-control",disabled = "disabled", @readonly = "readonly" } })*@
                @Html.ValidationMessageFor(model => model.MaNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.HoNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.TenNV, "Tên nhân viên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.GioiTinh, "Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    Nam @Html.RadioButtonFor(model => model.GioiTinh, "True", new { @checked = "checked" }) &nbsp;
                    Nữ @Html.RadioButtonFor(model => model.GioiTinh, "False")
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>

            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.NgaySinh, "Ngày sinh", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.Luong, "Tiền lương", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Luong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Luong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.AnhNV, "Ảnh đại diện", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" style="height:30px;" name="Avatar" accept="image/*" required />
                @Html.ValidationMessageFor(model => model.AnhNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.DiaChi, "Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            @Html.LabelFor(model => model.MaPB, "Phòng ban", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaPB", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group1">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm mới" class="btn btn-default" />

            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Quay lại", "Index")
</div>

Bt_Th_6/Views/NhanVien63132691/Delete.cshtml
@model Bt_Th_6.Models.NhanVien

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Luong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Luong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhongBan.TenPB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhongBan.TenPB)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Bt_Th_6/Views/NhanVien63132691/Details.cshtml
@model Bt_Th_6.Models.NhanVien

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>NhanVien</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HoNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioiTinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioiTinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgaySinh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgaySinh)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Luong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Luong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhNV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhNV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhongBan.TenPB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhongBan.TenPB)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaNV }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Bt_Th_6/Views/NhanVien63132691/Edit.cshtml
@model Bt_Th_6.Models.NhanVien

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NhanVien</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaNV)

        <div class="form-group">
            @Html.LabelFor(model => model.HoNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GioiTinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgaySinh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgaySinh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgaySinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Luong, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Luong, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Luong, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AnhNV, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AnhNV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AnhNV, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaPB, "MaPB", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaPB", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaPB, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bt_Th_6/Views/NhanVien63132691/Index.cshtml
@model IEnumerable<Bt_Th_6.Models.NhanVien>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    string gtinh = "";
    int i = 0;
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenNV", rowsPerPage: 5);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")
}

<h3>DANH SÁCH NHÂN VIÊN</h3>

<p>
    @Html.ActionLink("Thêm mới", "Create")|@Html.ActionLink("In danh sách", "PrintList")
</p>
@*<table class="table">
    <tr>
        <th>
            STT
        </th>
        <th>
            Mã NV
        </th>
        <th>
            Họ nhân viên
        </th>
        <th>
            Tên nhân viên
        </th>
        <th>
            Giới tính
        </th>
        <th>
            Ngày sinh
        </th>
        <th>
            Lương
        </th>
        <th>
            Ảnh NV
        </th>
        <th>
            Địa chỉ
        </th>
        <th>
            Phòng ban
        </th>
        <th>Chức năng</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @{i++;}
                @i
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaNV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoNV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenNV)
            </td>
            <td>
                @{if (item.GioiTinh == true)
                    { gtinh = "Nam"; }
                    else
                    { gtinh = "Nữ"; }
                }
                @gtinh

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgaySinh)

            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Luong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AnhNV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhongBan.TenPB)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaNV }) |
                @Html.ActionLink("Xem chi tiết", "Details", new { id = item.MaNV }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.MaNV })
            </td>
        </tr>
    }*@
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
              columns: new[]  // colums in grid
             {
         grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
        grid.Column("MaNV","Mã nhân viên"), //the model fields to display
        grid.Column("HoNV","Họ nhân viên"  ),
        grid.Column("TenNV","Tên nhân viên"),
        grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
        grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("Luong","Tiền lương",format:@<text> @item.Luong.ToString("#,##0")</text>),
grid.Column("DiaChi","Địa chỉ"),
grid.Column("PhongBan.TenPB","Phòng ban"),
grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "NhanVien63132691",new { id = item.MaNV },"NhanVien63132691Controller")),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","NhanVien63132691", new { id = item.MaNV },"NhanVien63132691Controller")),
grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","NhanVien63132691", new { id = item.MaNV },"NhanVienViensController")),
grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Edit",
                    new { id = item.MaNV})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Details",
                    new { id = item.MaNV})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Delete",
                    new { id = item.MaNV})" class="edit-btn">
        <abbr title="Xóa dữ liệu">
            <img src="/images/delete.png" width="20" height="20" />
        </abbr>
    </a>
</text>),

}
)
    </div>

</table>

Bt_Th_6/Views/NhanVien63132691/TimKiem63132691.cshtml
@model List<Bt_Th_6.Models.NhanVien>
@{
    ViewBag.Title = "TimKiem63132691";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    var grid = new WebGrid(Model, canPage: true, defaultSort: "TenNV", rowsPerPage: 5);
    @Scripts.Render("~/Scripts/jquery-1.6.2.min.js")

}
<html>
<head>
    <style type="text/css">
        .grid-footer {
            color: #000;
            font: 17px Calibri;
            text-align: center;
            font-weight: bold;
        }

            .grid-footer a {
                background-color: #ffffff;
                color: blue;
                box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                padding: 1px 10px 2px 10px;
            }

                .grid-footer a:active, a:hover {
                    background-color: #ffffff;
                    color: #FFAD33;
                    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
                }

        .alternatingRowStyle {
            background-color: aliceblue;
        }

        table .table1 {
            text-align: left;
            margin-left: 0px;
            margin-right: 0px;
            width: 800px;
        }

        .tr, .td {
            text-align: left;
        }
    </style>
</head>
<body>
    <div>
        @using (Html.BeginForm("TimKiem63132691", "NhanVien63132691", FormMethod.Get))
        {
            @Html.AntiForgeryToken()


        <table class="table1" align="center">
            <tr>
                <td>
                    <div> Mã nhân viên</div>
                </td>
                <td>
                    <input type="text" name="maNV" value="@ViewBag.maNV" />
                </td>

            </tr>
            <tr>
                <td>Họ tên</td>
                <td>
                    <input type="text" name="hoTen" value="@ViewBag.hoTen" />
                </td>

            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="submit" value="Tìm kiếm" style="margin-left: 5px;width:100px;
background-color: blue;color:white" />
                    <input type="button" name="Nhapmoi" value="Nhập mới" style="margin-left: 5px;width:100px;
background-color: blue;color:white" onclick="location.href='@Url.Action("TimKiem63132691", "NhanVien63132691/TimKiem63132691")'" />

                </td>
            </tr>

        </table>
        }
    </div>
    <div id="gridContent">
        @ViewBag.TB
        @grid.GetHtml(
            tableStyle: "table table-bordered table-hover",
            footerStyle: "grid-footer",
            fillEmptyRows: true,
            mode: WebGridPagerModes.Numeric,
            alternatingRowStyle: "alternatingRowStyle",
              columns: new[]  // colums in grid
             {
         grid.Column("STT",format: item => item.WebGrid.Rows.IndexOf(item) + 1 + Math.Round(Convert.ToDouble(grid.TotalRowCount / grid.PageCount) / grid.RowsPerPage) * grid.RowsPerPage * grid.PageIndex),
        grid.Column("MaNV","Mã nhân viên"), //the model fields to display
        grid.Column("HoNV","Họ nhân viên"  ),
        grid.Column("TenNV","Tên nhân viên"),
        grid.Column("GioiTinh","Giới tính",format: (@item) => @item.GioiTinh==true?"Nam":"Nữ"),
        grid.Column("NgaySinh","Ngày sinh",format:@<text> @item.NgaySinh.ToString("dd/MM/yyyy")</text>),
grid.Column("Luong","Tiền lương",format:@<text> @item.Luong.ToString("#,##0")</text>),
grid.Column("DiaChi","Địa chỉ"),
grid.Column("PhongBan.TenPB","Phòng ban"),
grid.Column(format: (item) => Html.ActionLink("Cập nhật", "Edit", "NhanVien63132691",new { id = item.MaNV },"NhanVien63132691Controller")),
grid.Column(format: (item) => Html.ActionLink("Xem chi tiết", "Details","NhanVien63132691", new { id = item.MaNV },"NhanVien63132691Controller")),
grid.Column(format: (item) => Html.ActionLink("Xóa", "Delete","NhanVien63132691", new { id = item.MaNV },"NhanVienViensController")),
grid.Column("Chức năng", format: @<text>
    <a href="@Url.Action("Edit",
                        new { id = item.MaNV})" class="edit-btn"><abbr title="Cập nhật dữ liệu"><img src="/images/edit.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Details",
                        new { id = item.MaNV})" class="edit-btn"><abbr title="Xem chi tiết"><img src="/images/details.png" width="20" height="20" /></abbr></a>
    <a href="@Url.Action("Delete",
                        new { id = item.MaNV})" class="edit-btn">
        <abbr title="Xóa dữ liệu">
            <img src="/images/delete.png" width="20" height="20" />
        </abbr>
    </a>
</text>),

}
)
    </div>
</body>
</html>